load("@io_bazel_rules_scala//scala:scala.bzl", "scala_library")

scala_library(
    name = "library",
    srcs = ["Example.scala"],
    deps = [],
)

scala_library(
    name = "secondary_library",
    srcs = ["SecondaryTargetSource.scala"],
    deps = [],
)
